export const ANIMUS_NAMES = [
  "Andrew [Odd]",
  "Andrew [Reason]",
  "Asshu",
  "Beyontin",
  "Borgne",
  "Cachi",
  "Cachi [The Guard]",
  "Celince",
  "Chiaki",
  "Chiaki [The Echo]",
  "Dinah",
  "Diting",
  "DokiDoki",
  "Dorothy",
  "Dorothy [The Wisher]",
  // "Fangus",
  // "Freya",
  // "Fuqiu",
  // "Gray",
  // "Heinrich",
  // "Helkid",
  // "Holden",
  // "Hoyan",
  // "Kazami Kazuyo",
  // "Kazuyo [The Reverie]",
  // "Khloros",
  // "Kloss",
  // "Kraken",
  // "Lian",
  // "Liliam",
  // "Lilith",
  // "Lily",
  // "Lingluo",
  // "Marvell",
  // "Massiah",
  // "Mia",
  // "Mio",
  // "Mizuki Makoto",
  // "Nahor",
  // "Nilu",
  // "No. 41",
  // "Obol",
  // "Oboro",
  // "RC-77",
  // "Rahu",
  // "Rilmocha",
  // "Rin",
  // "Rin [The Unbowed]",
  // "Rosa",
  // "Sania",
  // "Sania [Vengeful Thorn]",
  // "Sybil",
  // "Tiamat",
  // "Tsukiyo Mi",
  // "Tsutomu",
  // "Turandot",
  // "Valerian",
  // "Veronika",
  // "Vice",
  // "Victor",
  // "Viper",
  // "Xiada",
  // "Yang",
  // "Yeli"
]